// ESLint — configuração plana (ESLint 9)
//
// O projeto mistura dois mundos: scripts clássicos que conversam por globais
// no `window` (data-store, supabase, src/api/*) e módulos ES (src/modules/*,
// app.js). Cada bloco declara o que é legítimo em cada um, para que `no-undef`
// sirva de verdade — é a regra que pega nome de global digitado errado, que
// hoje quebra em silêncio no navegador.

import globals from 'globals';

// Globais compartilhadas entre os scripts clássicos do projeto.
const globaisDoProjeto = {
  '$': 'writable',
  'ADVERTENCIAS': 'writable',
  'AFASTAMENTOS': 'writable',
  'ANIV_MESES': 'writable',
  'Advertencias': 'writable',
  'Afastamentos': 'writable',
  'Auth': 'writable',
  'CLIMA': 'writable',
  'COLABORADORES': 'writable',
  'CONFIG': 'writable',
  'CONTATOS_EMERG': 'writable',
  'Cache': 'writable',
  'Cargos': 'writable',
  'Chart': 'writable',
  'Colaboradores': 'writable',
  'Configuracoes': 'writable',
  'ContatosEmergencia': 'writable',
  'Cronograma': 'writable',
  'DEPENDENTES': 'writable',
  'DESLIGAMENTOS': 'writable',
  'Dashboard': 'writable',
  'Departamentos': 'writable',
  'Desligamentos': 'writable',
  'EPI_CATALOGO': 'writable',
  'EPI_ENTREGAS': 'writable',
  'EPI_KITS': 'writable',
  'EVENTOS': 'writable',
  'Epis': 'writable',
  'FAIXAS': 'writable',
  'FEEDBACK': 'writable',
  'FERIAS': 'writable',
  'FeedbackClima': 'writable',
  'Ferias': 'writable',
  'HistoricoColaboradores': 'writable',
  'PARENTESCO_OPTS': 'writable',
  'PC_CARGOS': 'writable',
  'PC_PLANOS': 'writable',
  'POLITICAS': 'writable',
  'PRESTADORES': 'writable',
  'PROCEDIMENTOS': 'writable',
  'PROLABORE': 'writable',
  'PlanoCarreiras': 'writable',
  'PoliticasEmpresa': 'writable',
  'PrestadoresServico': 'writable',
  'ProcedimentosEmpresa': 'writable',
  'ProlaboreSocios': 'writable',
  'ROTATIVIDADE': 'writable',
  'RespostasPesquisa': 'writable',
  'Rotatividade': 'writable',
  'SAC': 'writable',
  'SALARIOS': 'writable',
  'SUPABASE_ANON': 'writable',
  'SUPABASE_URL': 'writable',
  'SacMensagens': 'writable',
  'Salarios': 'writable',
  'StorageDocs': 'writable',
  'Treinamentos': 'writable',
  'VALE_ALIMENTACAO': 'writable',
  'VALE_COTAS': 'writable',
  'VALE_COTAS_MES': 'writable',
  'VALE_DESCONTOS': 'writable',
  'VALE_LANCAMENTOS': 'writable',
  'VALE_SALDO_INI': 'writable',
  'VALE_USO_MES': 'writable',
  'VA_BENEFICIOS': 'writable',
  'VENCIMENTOS': 'writable',
  'ValeAlimentacao': 'writable',
  'ValeCombustivel': 'writable',
  'ValeDescontos': 'writable',
  'Vencimentos': 'writable',
  '_anivMesVisto': 'writable',
  '_chartRot': 'writable',
  '_filtrarArray': 'writable',
  '_popupVencDismissed': 'writable',
  '_preencherArray': 'writable',
  '_upsertArray': 'writable',
  'abrirModalAniversariantes': 'writable',
  'abrirVencimentosDoPopup': 'writable',
  'atualizarBadgeSac': 'writable',
  'atualizarBadgeVencimentos': 'writable',
  'atualizarTopbarUsuario': 'writable',
  'autenticadoAntes': 'writable',
  'coletarFalhas': 'writable',
  'descreverErro': 'writable',
  'diasAte': 'writable',
  'dispensarFalhasCarregamento': 'writable',
  'fazerLogout': 'writable',
  'fecharModalAniversariantes': 'writable',
  'fecharPopupVencimentos': 'writable',
  'fmtBRL': 'writable',
  'goPage': 'writable',
  'h': 'writable',
  'handleLogin': 'writable',
  'inicializarSupabase': 'writable',
  'irParaVencimento': 'writable',
  'makeCache': 'writable',
  'mapAdvertencia': 'writable',
  'mapColaborador': 'writable',
  'mapDesligamento': 'writable',
  'mapEvento': 'writable',
  'mapFerias': 'writable',
  'mostrarFalhasCarregamento': 'writable',
  'mostrarPopupVencimentos': 'writable',
  'navAniversariantes': 'writable',
  'popularFiltrosSetor': 'writable',
  'renderAdvertencias': 'writable',
  'renderAll': 'writable',
  'renderBeneficios': 'writable',
  'renderClima': 'writable',
  'renderColaboradores': 'writable',
  'renderCronograma': 'writable',
  'renderDashboard': 'writable',
  'renderDashboardCharts': 'writable',
  'renderDesligamentos': 'writable',
  'renderEpi': 'writable',
  'renderEpiCatalogo': 'writable',
  'renderEpiKits': 'writable',
  'renderFeedback': 'writable',
  'renderFerias': 'writable',
  'renderModalAniversariantes': 'writable',
  'renderPlanoCarreiras': 'writable',
  'renderPoliticas': 'writable',
  'renderPrestadores': 'writable',
  'renderProcedimentos': 'writable',
  'renderProlabore': 'writable',
  'renderQuadro': 'writable',
  'renderRotatividade': 'writable',
  'renderSac': 'writable',
  'renderSacTratativas': 'writable',
  'renderSalarios': 'writable',
  'renderVale': 'writable',
  'renderValeAlimentacao': 'writable',
  'renderVencimentos': 'writable',
  'resumirFalhas': 'writable',
  'sb': 'writable',
  'setupRealTimeListeners': 'writable',
  'showToast': 'writable',
  'supabase': 'writable',
  'vencimentosUrgentes': 'writable',
  'verificarSessao': 'writable',
  'withRetry': 'writable',
  'withTimeout': 'writable',
};

// Conjunto mínimo e de alto sinal: cada regra corresponde a um erro que passa
// despercebido no navegador. Nada de estilo — isso vira ruído em CI.
const regrasBase = {
  'no-undef': 'error',
  'no-dupe-keys': 'error',
  'no-dupe-args': 'error',
  'no-dupe-else-if': 'error',
  'no-unreachable': 'error',
  'no-cond-assign': 'error',
  'no-constant-condition': 'error',
  'no-self-compare': 'error',
  'no-unsafe-negation': 'error',
  'no-async-promise-executor': 'error',
  'no-compare-neg-zero': 'error',
  'no-empty': ['error', { allowEmptyCatch: true }],
  'no-fallthrough': 'error',
  'no-func-assign': 'error',
  'no-import-assign': 'error',
  'no-obj-calls': 'error',
  'no-sparse-arrays': 'error',
  'use-isnan': 'error',
  'valid-typeof': 'error',
  'no-prototype-builtins': 'error',
  'require-atomic-updates': 'error',
};

export default [
  { ignores: ['coverage/**', 'node_modules/**', 'database/migrations/**', '_site/**'] },

  // ─── Scripts clássicos ─────────────────────────────────────────────────────
  // Aqui declarar no topo do arquivo É a interface pública: `no-redeclare` e
  // `no-unused-vars` não conseguem enxergar o consumo entre arquivos, então
  // ficam desligado e como aviso. `no-undef` continua valendo, e é o que importa.
  {
    files: [
      'supabase.js', 'src/data-store.js', 'src/dashboard.js', 'src/auth.js',
      'src/utils/base.js', 'src/utils/carregamento.js', 'src/utils/rede.js',
      'src/utils/mappers.js', 'src/utils/relatorio.js', 'src/utils/arrays.js',
      'src/api/*.js',
    ],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'script',
      globals: { ...globals.browser, ...globaisDoProjeto },
    },
    rules: {
      ...regrasBase,
      'no-redeclare': 'off',
      'no-unused-vars': ['warn', { args: 'none', varsIgnorePattern: '^_' }],
    },
  },

  // ─── Módulos ES ────────────────────────────────────────────────────────────
  // Escopo fechado: aqui as duas regras acima são precisas e valem como erro.
  {
    files: ['src/app.js', 'src/constants.js', 'src/modules/*.js', 'src/utils/formatting.js'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'module',
      globals: { ...globals.browser, Chart: 'readonly' },
    },
    rules: {
      ...regrasBase,
      'no-redeclare': 'error',
      'no-unused-vars': ['error', { args: 'none', varsIgnorePattern: '^_' }],
    },
  },

  // ─── Testes ────────────────────────────────────────────────────────────────
  {
    files: ['tests/**/*.js'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'module',
      globals: { ...globals.node, ...globals.browser },
    },
    rules: { ...regrasBase, 'no-unused-vars': 'warn' },
  },
];
